#!/usr/bin/env python3
"""Build a region species list for any place on Earth from GBIF bird observations.

Keeps the model's species that have been recorded within --radius km of the location,
and looks up local names in --lang (ISO 639-2 code, e.g. swe, deu, fra, eng).

    python3 scripts/make_region.py --lat 57.7089 --lon 11.9746 --radius 15 --lang swe \
        --out gibbird/data/regions/my_place.csv

Then set `region = "my_place"` (or the CSV path) in config.toml. The output includes
seabirds, waders etc. that will never land on a balcony: prune it by hand, and raise
--min-records to drop rarities. The curated gothenburg.csv is an example.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from urllib.parse import urlencode
from urllib.request import urlopen

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from gibbird.names import load_labels  # noqa: E402

API = "https://api.gbif.org/v1"
AVES = 212  # GBIF class key for birds


def get(path: str, **params) -> dict:
    with urlopen(f"{API}{path}?{urlencode(params)}", timeout=30) as r:
        return json.load(r)


def region_counts(lat: float, lon: float, radius_km: float) -> dict[int, int]:
    dlat = radius_km / 111.0
    dlon = radius_km / (111.0 * math.cos(math.radians(lat)))
    data = get(
        "/occurrence/search",
        classKey=AVES,
        decimalLatitude=f"{lat - dlat},{lat + dlat}",
        decimalLongitude=f"{lon - dlon},{lon + dlon}",
        occurrenceStatus="PRESENT",
        facet="speciesKey",
        facetLimit=3000,
        limit=0,
    )
    return {int(c["name"]): c["count"] for c in data["facets"][0]["counts"]} if data["facets"] else {}


def species_key(sci: str) -> int | None:
    m = get("/species/match", name=sci, **{"class": "Aves"})
    return m.get("speciesKey") if m.get("matchType") != "NONE" else None


def local_name(key: int, lang: str) -> str:
    names = get(f"/species/{key}/vernacularNames", limit=300)["results"]
    for n in names:
        if n.get("language") == lang:
            v = n["vernacularName"].strip()
            return v[:1].upper() + v[1:]
    return ""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--lat", type=float, required=True)
    ap.add_argument("--lon", type=float, required=True)
    ap.add_argument("--radius", type=float, default=15, help="km (default 15)")
    ap.add_argument("--lang", default="eng", help="ISO 639-2 language for local names (default eng)")
    ap.add_argument("--min-records", type=int, default=50, help="drop species seen fewer times")
    ap.add_argument("--labels", default="models/inat_bird_labels.txt")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    labels = [lbl for lbl in load_labels(args.labels).values() if not lbl.is_background]
    print(f"fetching GBIF observations around {args.lat}, {args.lon} ...", file=sys.stderr)
    counts = region_counts(args.lat, args.lon, args.radius)
    print(f"{len(counts)} bird species recorded; matching {len(labels)} model labels ...", file=sys.stderr)

    with ThreadPoolExecutor(8) as pool:
        keys = list(pool.map(lambda lbl: species_key(lbl.sci), labels))
    found = [(lbl, k, counts[k]) for lbl, k in zip(labels, keys) if k and counts.get(k, 0) >= args.min_records]

    # Several model labels (subspecies, domestic forms) can map to one species: keep the
    # plain species as canonical and list the rest as aliases.
    by_key: dict[int, list] = {}
    for lbl, k, n in found:
        by_key.setdefault(k, []).append((lbl, n))
    with ThreadPoolExecutor(8) as pool:
        locals_ = dict(zip(by_key, pool.map(lambda k: local_name(k, args.lang), by_key)))

    rows = []
    for k, entries in by_key.items():
        entries.sort(key=lambda e: len(e[0].sci.split()))
        main_lbl, n = entries[0]
        aliases = ";".join(e[0].sci for e in entries[1:])
        rows.append((n, main_lbl.sci, main_lbl.common, locals_[k], aliases))
    rows.sort(reverse=True)

    with open(args.out, "w", newline="", encoding="utf-8") as f:
        f.write(f"# Generated by make_region.py: lat={args.lat} lon={args.lon} radius={args.radius}km "
                f"min_records={args.min_records}. Sorted by number of GBIF records.\n")
        w = csv.writer(f)
        w.writerow(["sci", "en", "local", "aliases"])
        for _, sci, en, loc, aliases in rows:
            w.writerow([sci, en, loc, aliases])
    print(f"wrote {len(rows)} species to {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
